name: Norminette Check
on:
  pull_request:
    branches: [ main, master ]

jobs:
  norminette:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
